### ISSUE TITLE
Fix font size discrepancy on quote and pullquote blocks

### ISSUE THREAD

**Issue by jessica-townsend** [thoughtis/cata#166]
The quote and pullquote blocks are both receiving this style from the parent theme:
```
.wp-block-pullquote cite,
.wp-block-quote cite {
	font-size: min(0.875em,1.25rem);
}
```

This overrides any font size settings in the editor to either of these blocks. The quote text itself changes size, but the citation text stays the same size. Can we remove this or set the `cite` element to inherit the font size of the parent block?

**Comment by douglas-johnson** [comment]
> Can we remove this or set the cite element to inherit the font size of the parent block?

Yes definitely, when you described the issue previously I didn't realize it was our code creating the problem.
