### ISSUE TITLE
Testing for WordPress 6.5

### ISSUE THREAD

**Issue by douglas-johnson** [thoughtis/cata#188]
I reviewed https://make.wordpress.org/core/tag/6-5/ 

This update seems mostly about new features like interactivity and block data binding, which are great opportunities but are unlikely to cause any issues with our existing themes. As a result this first round of testing is pretty lightweight. Let's test again when the field guide is out.

## Things to Test

Note any errors or warnings in the browser console, server error log or query monitor while testing these things:

- [ ] Edit a post
- [ ] Create a new post with each of the Cata Blocks in it.
- [ ] Add or Edit a page
- [ ] Edit a user
- [ ] Change a user's role
- [ ] Edit a guest author
- [ ] Add or Edit a Reusable Block ( now called Synced Patterns ) on a site where we added a link in the admin nav.

## Things to Check

- [ ] Are there any top-level CSS changes ( like the switching to `:where()` that bit us last time )?

**Comment by jessica-townsend** [comment]
Closing since 6.5 has been released
