### ISSUE TITLE
Add Support for Cover Block

### ISSUE THREAD

**Issue by douglas-johnson** [thoughtis/cata#51]
### Background

I have avoided supporting the Cover Block so far because:
- It has a large number of customizable settings.
- Uses style attribute for some of those features
- Uses background-image which isn't responsive in the `srcset` sense and isn't lazy loaded.

But, the new design of the Shop Catalog homepage uses something very similar, so it would be a little silly to build a custom block to support most of the same features.

Can we do anything to address the responsiveness and lazy loading?

The distributed CSS is here, it should give us a good idea of all the possible modifications a user can make:
https://github.com/WordPress/WordPress/blob/5.7/wp-includes/css/dist/block-library/style.css#L369-L673

**Comment by richdacuban** [comment]
- `.has-background-dim-30` not supported
- `.has-background-gradient` not supported
